version: "3"

services:
  
  promoshock-api:
    image: ghcr.io/kelizarov/promoshock-api:latest
    container_name: promoshock-api
    build:
      context: ./backend
    env_file: 
      - .env
    environment:
      - DB_HOST=${POSTGRES_HOST}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - TICKET_FACTORY_ADDR=${TICKET_FACTORY_ADDR}
      - PROMO_FACTORY_ADDR=${PROMO_FACTORY_ADDR}
      - ENV=${APP_ENV}
    networks:
      - promoshock
    ports:
      - "5005:80"
    depends_on: 
      - db
    restart: always

  db:
    image: postgres:9.6
    container_name: postgres
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - promoshock

volumes:
  postgres-data:
    driver: local

networks:
  promoshock:
