version: "3"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    restart: always
    environment:
      - DB_HOST=postgres
      - DB_PASSWORD=pass
      - TICKET_FACTORY_ADDR=0x42C593A0F50321EA473b5fAe6a4b76c212a26F54
      - PROMO_FACTORY_ADDR=0x3d3E2D37151a812418FB075190f959a6C90C3A38
      - ENV=DEVELOPMENT
    volumes:
      - ./:/code
      - ../contracts/abi:/contracts/abi
    ports:
      - "5005:80"

  postgres:
    image: postgres:9.6
    environment:
      - POSTGRES_USER=metastream
      - POSTGRES_PASSWORD=pass
    ports:
      - "54321:5432"
