---
openapi: 3.1.0
info:
  title: FastAPI
  version: 0.1.0
paths:
  "/index/start":
    post:
      summary: Start Index
      operationId: start_index_index_start_post
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
  "/ticket":
    get:
      summary: All Tickets
      operationId: all_tickets_ticket_get
      parameters:
      - name: offset
        in: query
        required: false
        schema:
          default: 0
          title: Offset
      - name: limit
        in: query
        required: false
        schema:
          default: 25
          title: Limit
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                type: array
                items:
                  "$ref": "#/components/schemas/Stream"
                title: Response All Tickets Ticket Get
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/HTTPValidationError"
  "/promo":
    get:
      summary: All Promos
      operationId: all_promos_promo_get
      parameters:
      - name: offset
        in: query
        required: false
        schema:
          default: 0
          title: Offset
      - name: limit
        in: query
        required: false
        schema:
          default: 25
          title: Limit
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/HTTPValidationError"
components:
  schemas:
    HTTPValidationError:
      properties:
        detail:
          items:
            "$ref": "#/components/schemas/ValidationError"
          type: array
          title: Detail
      type: object
      title: HTTPValidationError
    Stream:
      properties:
        sale_address:
          type: string
          format: binary
          title: Sale Address
        owner_address:
          type: string
          format: binary
          title: Owner Address
        name:
          type: string
          title: Name
        description:
          type: string
          title: Description
        banner:
          type: string
          title: Banner
        start_date:
          type: integer
          title: Start Date
        sale_start_date:
          type: integer
          title: Sale Start Date
        sale_end_date:
          type: integer
          title: Sale End Date
        link:
          type: string
          title: Link
        streamer_link:
          type: string
          title: Streamer Link
        price:
          type: integer
          title: Price
        total_amount:
          type: integer
          title: Total Amount
        reserved_amount:
          type: integer
          title: Reserved Amount
      type: object
      required:
      - sale_address
      - owner_address
      - name
      - description
      - banner
      - start_date
      - sale_start_date
      - sale_end_date
      - link
      - streamer_link
      - price
      - total_amount
      - reserved_amount
      title: Stream
    ValidationError:
      properties:
        loc:
          items:
            anyOf:
            - type: string
            - type: integer
          type: array
          title: Location
        msg:
          type: string
          title: Message
        type:
          type: string
          title: Error Type
      type: object
      required:
      - loc
      - msg
      - type
      title: ValidationError
