---
openapi: 3.1.0
info:
  title: FastAPI
  version: 0.1.0
paths:
  "/index/start":
    post:
      summary: Start Index
      operationId: start_index_index_start_post
      parameters:
      - name: from_block
        in: query
        required: false
        schema:
          enum:
          - latest
          - earliest
          - pending
          - safe
          - finalized
          type: string
          default: 37553211
          title: From Block
      - name: to_block
        in: query
        required: false
        schema:
          enum:
          - latest
          - earliest
          - pending
          - safe
          - finalized
          type: string
          default: latest
          title: To Block
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/HTTPValidationError"
  "/index/ticket":
    post:
      summary: Index Ticket
      operationId: index_ticket_index_ticket_post
      parameters:
      - name: from_block
        in: query
        required: false
        schema:
          enum:
          - latest
          - earliest
          - pending
          - safe
          - finalized
          type: string
          default: 37553211
          title: From Block
      - name: to_block
        in: query
        required: false
        schema:
          enum:
          - latest
          - earliest
          - pending
          - safe
          - finalized
          type: string
          default: latest
          title: To Block
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/HTTPValidationError"
  "/index/promo":
    post:
      summary: Index Promo
      operationId: index_promo_index_promo_post
      parameters:
      - name: from_block
        in: query
        required: false
        schema:
          enum:
          - latest
          - earliest
          - pending
          - safe
          - finalized
          type: string
          default: 37553211
          title: From Block
      - name: to_block
        in: query
        required: false
        schema:
          enum:
          - latest
          - earliest
          - pending
          - safe
          - finalized
          type: string
          default: latest
          title: To Block
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/HTTPValidationError"
  "/ticket":
    get:
      summary: All Tickets
      operationId: all_tickets_ticket_get
      parameters:
      - name: owner
        in: query
        required: false
        schema:
          title: Owner
      - name: offset
        in: query
        required: false
        schema:
          default: 0
          title: Offset
      - name: limit
        in: query
        required: false
        schema:
          default: 25
          title: Limit
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                type: array
                items:
                  "$ref": "#/components/schemas/Stream"
                title: Response All Tickets Ticket Get
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/HTTPValidationError"
  "/ticket/{ticket_addr}":
    get:
      summary: Get Stream
      operationId: get_stream_ticket__ticket_addr__get
      parameters:
      - name: ticket_addr
        in: path
        required: true
        schema:
          type: string
          title: Ticket Addr
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                anyOf:
                - "$ref": "#/components/schemas/Stream"
                - type: 'null'
                title: Response Get Stream Ticket  Ticket Addr  Get
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/HTTPValidationError"
  "/promo":
    get:
      summary: All Promos
      operationId: all_promos_promo_get
      parameters:
      - name: stream
        in: query
        required: false
        schema:
          title: Stream
      - name: owner
        in: query
        required: false
        schema:
          title: Owner
      - name: offset
        in: query
        required: false
        schema:
          default: 0
          title: Offset
      - name: limit
        in: query
        required: false
        schema:
          default: 25
          title: Limit
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/HTTPValidationError"
components:
  schemas:
    HTTPValidationError:
      properties:
        detail:
          items:
            "$ref": "#/components/schemas/ValidationError"
          type: array
          title: Detail
      type: object
      title: HTTPValidationError
    Stream:
      properties:
        owner_address:
          type: string
          format: binary
          title: Owner Address
        sale_address:
          type: string
          format: binary
          title: Sale Address
        ticket_address:
          type: string
          format: binary
          title: Ticket Address
        payment_token_address:
          type: string
          format: binary
          title: Payment Token Address
        name:
          type: string
          title: Name
        description:
          type: string
          title: Description
        banner:
          type: string
          title: Banner
        start_date:
          type: integer
          title: Start Date
        sale_start_date:
          type: integer
          title: Sale Start Date
        sale_end_date:
          type: integer
          title: Sale End Date
        stream_link:
          type: string
          title: Stream Link
        streamer_link:
          type: string
          title: Streamer Link
        price:
          type: string
          title: Price
        total_amount:
          type: integer
          title: Total Amount
        reserved_amount:
          type: integer
          title: Reserved Amount
        purchased:
          type: boolean
          title: Purchased
      type: object
      required:
      - owner_address
      - sale_address
      - ticket_address
      - payment_token_address
      - name
      - description
      - banner
      - start_date
      - sale_start_date
      - sale_end_date
      - stream_link
      - streamer_link
      - price
      - total_amount
      - reserved_amount
      - purchased
      title: Stream
    ValidationError:
      properties:
        loc:
          items:
            anyOf:
            - type: string
            - type: integer
          type: array
          title: Location
        msg:
          type: string
          title: Message
        type:
          type: string
          title: Error Type
      type: object
      required:
      - loc
      - msg
      - type
      title: ValidationError
