name: deploy-api

on:
  push:
    branches: ["main"]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.actor }}/promoshockapi:latest

jobs:
  publish:
    name: build and upload image
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: install ssh keys
      run: |
        install -m 600 -D /dev/null ~/.ssh/id_ed25519
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
        ssh-keyscan -H ${{ secrets.SSH_HOST }} > ~/.ssh/known_hosts
    - name: Build and Publish
      run: |
        docker build backend --tag ${{ env.IMAGE_NAME }}
        docker save ${{ env.IMAGE_NAME }} | ssh -C ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "docker load && cd ${{ env.WORKDIR }} && docker compose -d && exit" 
    - name: cleanup
      run: rm -rf ~/.ssh

